### ISSUE TITLE
App for Switch discord status says offline

### ISSUE THREAD

**Issue by RainingLotus37** [MCMi460/NSO-RPC#32] opened 2022-08-16 20:09 UTC
So I linked my nintendo account, but the app says I am offline, and I am not. Can't seem to see a fix?

**Comment by samuelthomas2774** [comment] 2022-08-16 20:33
Are you using your own account that you want to share the presence of? You need to link a secondary account that is friends with your main account, not your main account directly, [as explained in the README](https://github.com/MCMi460/NSO-RPC#quickstart-guide).

See https://github.com/samuelthomas2774/nxapi/issues/1 and [MCMi460/NSO-RPC#13](https://github.com/MCMi460/NSO-RPC/issues/13) for more information on why this is necessary.

(Duplicate of https://github.com/MCMi460/NSO-RPC/issues/13, https://github.com/MCMi460/NSO-RPC/issues/15, https://github.com/MCMi460/NSO-RPC/issues/16, https://github.com/MCMi460/NSO-RPC/issues/26, https://github.com/MCMi460/NSO-RPC/issues/31.)

**Comment by RainingLotus37** [comment] 2022-08-16 20:39
Okay thanks, I wasn't sure what that meant. I'll try that :)

**Comment by MCMi460** [comment] 2022-08-17 21:10
Thank you, @samuelthomas2774!

**Closed by MCMi460** 2022-08-17 21:10 UTC
