### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by LewiFF** [MCMi460/NSO-RPC#49] opened 2022-10-09 15:56 UTC
I keep getting this error :
Launch error
See the py2app website for debugging launch issues

**Comment by MCMi460** [comment] 2022-10-10 18:37
As of recently, I've been receiving a lot of `9403` errors from the app. What I did to fix this was delete the `~/Documents/NSO-RPC/tempToken.txt` and `~/Documents/NSO-RPC/private.txt` files, then try logging back in.
I've also just pushed 24925d65a0d129a90959e0a422ab19b244d486e8 which fixed another error I had been receiving due to my poor thinking when writing that section of code. If you are still receiving errors after trying a few times, check your `logs.txt` file in the same directory as mentioned above and send here what the newest error is. It may be that the latest commit fixes your issue.
I'm sorry again for the inconvenience caused by this.

**Comment by LewiFF** [comment] 2022-10-21 17:43
Yeah Thank you. But it doesnt show up that im online

**Comment by finnmayhew** [comment] 2022-12-19 18:49
Hi, not the OP, but getting the same behavior.  I'm on an M1 Mac, and have set the app to open at login.  Here's the error I get.  Maybe it's trying to connect before my computer has established an internet connection?

```
1671475647.867906: Failed to get Apple's store page. Retrying...
1671475647.867906: Failed to get Apple's store page. Retrying...
1671475647.867906: Failed to get Apple's store page. Retrying...
1671475647.867906: Failed to get Apple's store page. Retrying...
1671475647.867906: Failed to get Apple's store page. Retrying...
```

**Comment by HotaruBlaze** [comment] 2022-12-20 00:03
The main repo hasn't been updated yet, theirs a fix in the development branch around getting the version info, however that will sometimes give you a error starting as well as the commit I did was flawed, theirs a better fix coming but it's currently stuck in limbo because it's part of autostart code that needs more testing on the macos side

**Comment by finnmayhew** [comment] 2022-12-20 00:28
Glad to hear that's on the way, thank y'all for your work!

**Comment by MCMi460** [comment] 2023-05-26 05:35
Now that this issue is fixed, I will be closing it. Please update me if any further problems ensue. Thank you!

**Closed by MCMi460** 2023-05-26 05:35 UTC
