### ISSUE TITLE
App crashing on start

### ISSUE THREAD

**Issue by OctoFloofy** [MCMi460/NSO-RPC#34] opened 2022-08-23 22:46 UTC
Traceback (most recent call last):
  File "cli.py", line 77, in update
  File "api\__init__.py", line 113, in getSelf
  File "api\__init__.py", line 126, in getFriends
  File "api\__init__.py", line 293, in populateList
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 561, in <module>
  File "app.py", line 151, in selfService
  File "app.py", line 258, in changeState
  File "cli.py", line 83, in update
  File "api\__init__.py", line 104, in updateLogin
KeyError: 'result'

**Comment by MCMi460** [comment] 2022-08-23 23:42
This is error code 9599, and the issue is that Nintendo is now requiring the timestamp sent in requests to match the one from the Android emulator used to generate the `f` token. This isn't a significant change, but we will have to wait until imink API (I'm still awaiting their approval) updates to adapt to these changes.
Sorry for the inconvenience, and thank you for your patience.

**Comment by JoneWang** [comment] 2022-08-24 06:37
@MCMi460 Hi. I've updated the [imink API documentation](https://github.com/JoneWang/imink/wiki/imink-API-Documentation). Hope it helps.

**Comment by Link0Darck** [comment] 2022-08-24 18:12
> @MCMi460 Hi. I've updated the [imink API documentation](https://github.com/JoneWang/imink/wiki/imink-API-Documentation). Hope it helps.

Hello,
I have the same problem and what you have marked no it doesn't help we don't know where to put in the .txt when we use the windows version

**Comment by MCMi460** [comment] 2022-08-24 18:18
> > @MCMi460 Hi. I've updated the [imink API documentation](https://github.com/JoneWang/imink/wiki/imink-API-Documentation). Hope it helps.
> 
> 
> 
> Hello,
> 
> I have the same problem and what you have marked no it doesn't help we don't know where to put in the .txt when we use the windows version

The issue will be solved in the next release, which will (hopefully) be today.
Sorry again for the trouble!

**Comment by Link0Darck** [comment] 2022-08-24 18:21
> > > @MCMi460 Hi. I've updated the [imink API documentation](https://github.com/JoneWang/imink/wiki/imink-API-Documentation). Hope it helps.
> > 
> > 
> > Hello,
> > I have the same problem and what you have marked no it doesn't help we don't know where to put in the .txt when we use the windows version
> 
> The issue will be solved in the next release, which will (hopefully) be today. Sorry again for the trouble!

I'm not sure how long it would take to fix your app and do you have a support discord or something like that?

**Comment by MCMi460** [comment] 2022-08-24 18:45
> > > > @MCMi460 Hi. I've updated the [imink API documentation](https://github.com/JoneWang/imink/wiki/imink-API-Documentation). Hope it helps.
> 
> > > 
> 
> > > 
> 
> > > Hello,
> 
> > > I have the same problem and what you have marked no it doesn't help we don't know where to put in the .txt when we use the windows version
> 
> > 
> 
> > The issue will be solved in the next release, which will (hopefully) be today. Sorry again for the trouble!
> 
> 
> 
> I'm not sure how long it would take to fix your app and do you have a support discord or something like that?

Er, I suppose I could create a support Discord server, but it wouldn't be very professional. Also, I'll finish updating the API classes internally this afternoon, and hopefully release the newest compiled app later today.

Here is the invite:
https://discord.gg/pwFASr2NKx

**Comment by MCMi460** [comment] 2022-08-25 23:24
This should be fixed in 8abf86c6f4dca2d5cde7bf0886de6f1642b6dbef. If you are still having troubles, please reopen this issue.

**Closed by MCMi460** 2022-08-25 23:24 UTC
